name: app_check_poc
description: "A flutter template project for new project's kick start."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dio:
  firebase_core: ^2.24.2
  firebase_app_check:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  internet_connection_checker: ^1.0.0+1
  master_utility: ^0.0.3
  provider: ^6.1.1


dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/colors/
    - assets/fonts/
    - prod.env
    - dev.env
    - stage.env

  fonts:
    - family: latoRegular
      fonts:
        - asset: assets/fonts/lato-regular.ttf


flutter_gen:
  output: lib/configs/assets/
  line_length: 80

  assets:
    enabled: true

    outputs:
      class_name: AppAssets
      package_parameter_enabled: false
      style: dot-delimiter

  fonts:
    enabled: true
    outputs:
      class_name: AppFonts

  colors:
    inputs:
      - assets/colors/colors.xml
    enabled: true
    outputs:
      class_name: AppColors

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true


