import 'package:provider/single_child_widget.dart';
// ignore_for_file: public_member_api_docs
// ignore_for_file: avoid_classes_with_only_static_members
class AppStrings {

  static const String appName = 'App Check';

  static List<SingleChildWidget> providers = [
  ];

  static const String whiteSpace = ' ';
  static const String cancelled = 'cancelled';
  static const String yes = 'Yes';
  static const String okay = 'Okay';
  static List<String> languagesList = [
    'Afrikaans',
    'Arabic',
    'Azeri',
    'Belarusian',
    'Catalan',
    'Czech',
    'Welsh',
    'Danish',
    'German',
    'Divehi',
    'Greek',
    'English',
    'Esperanto',
    'Spanish',
    'Estonian',
    'Basque',
    'Farsi',
    'Finnish',
    'Faroese',
    'French',
    'Galician',
    'Gujarati',
    'Hebrew',
    'Hindi',
    'Croatian',
    'Hungarian',
    'Armenian',
    'Indonesian',
    'Icelandic',
    'Italian',
    'Japanese',
    'Georgian',
    'Kazakh',
    'Kannada',
    'Korean',
    'Konkani',
    'Kyrgyz',
    'Lithuanian',
    'Latvian',
    'Maori',
    'FYRO Macedonian',
    'Mongolian',
    'Marathi',
    'Malay',
    'Maltese',
    'Norwegian',
    'Dutch',
    'NO Norwegian',
    'Northern Sotho',
    'ZA Northern Sotho',
    'Punjabi',
    'Polish',
    'Pashto',
    'Portuguese',
    'Quechua',
    'Romanian',
    'Russian',
    'Sanskrit',
    'Sami',
    'Slovak',
    'Slovenian',
    'Albanian',
    'BA Serbian',
    'SP Serbian',
    'Swedish',
    'Swahili',
    'Syriac',
    'Tamil',
    'Telugu',
    'Thai',
    'Tagalog',
    'Tswana',
    'Turkish',
    'Tatar',
    'Tsonga',
    'Ukrainian',
    'Urdu',
    'Uzbek',
    'Vietnamese',
    'Xhosa',
    'ZA Xhosa',
    'Chinese',
    'Zulu',
  ];
}
